INSERT INTO ASSET ("ID", "ASSET_NAME", "CURRENCY", "SIZE", "USABLE_SIZE", "CUSTOMER_ID", "CREATED_AT") VALUES (1, 'ASSET A', 0, 100, 100, 1, NOW());
INSERT INTO ASSET ("ID", "ASSET_NAME", "CURRENCY", "SIZE", "USABLE_SIZE", "CUSTOMER_ID", "CREATED_AT") VALUES (2, 'ASSET B', 0, 150, 150, 2, NOW());
INSERT INTO ASSET ("ID", "ASSET_NAME", "CURRENCY", "SIZE", "USABLE_SIZE", "CUSTOMER_ID", "CREATED_AT") VALUES (3, 'ASSET C', 0, 200, 200, 3, NOW());
INSERT INTO ASSET ("ID", "ASSET_NAME", "CURRENCY", "SIZE", "USABLE_SIZE", "CUSTOMER_ID", "CREATED_AT") VALUES (4, 'ASSET D', 0, 250, 250, 4, NOW());
INSERT INTO ASSET ("ID", "ASSET_NAME", "CURRENCY", "SIZE", "USABLE_SIZE", "CUSTOMER_ID", "CREATED_AT") VALUES (5, 'ASSET E', 0, 300, 300, 5, NOW());

